spring.datasource.url=jdbc:postgresql://localhost:5433/petpal
spring.datasource.username=postgres
spring.datasource.password=Naruto2002!

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Make Spring run schema.sql + data.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
