spring.application.name=petpal
server.port=9090

# ================
# FIREBASE
# ================
# Set this ENV variable:
# FIREBASE_CONFIG_PATH=C:/firebase/petpal-key.json
firebase.config.path="C:\firebase\petpal-e5d41-firebase-adminsdk-fbsvc-0e9e306a7c.json"

# ================
# DISABLE SQL COMPLETELY
# ================
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.petpal=DEBUG
