spring.application.name=petpal
server.port=8080

# ================
# FIREBASE
# ================
# Set this ENV variable:
# FIREBASE_CONFIG_PATH=C:/firebase/petpal-key.json
firebase.config.path="C:\firebase\petpal-e5d41-firebase-adminsdk-fbsvc-0e9e306a7c.json"

# ================
# DISABLE SQL COMPLETELY
# ================
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


# ===============
# ADDED THE MAIL PROPERTIES
# ===============
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-project-email@gmail.com
spring.mail.password=your-app-password-here
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Logging
logging.level.org.springframework=INFO
logging.level.com.example.petpal=DEBUG
